import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full border-b border-gray-300 h-12 bg-white flex items-center px-2 shadow-sm">
          <Image
            src="/LogoV2.svg"
            width={350}
            height={50}
            alt="Double Droppr Logo"
          />
        </div>
        {children}
      </body>
    </html>
  );
}
